### ISSUE TITLE
WatchOS in Receive method not working

### ISSUE THREAD

**Issue by VocsyAniket** [webrror/watchos_flutter_test#2]
Hii Bro,
watch to iphone in send message perfect but iphone to watch send message not working
please give me any suggestion?

**Comment by webrror** [comment]
@VocsyAniket can I get the output for `flutter doctor` ?

**Comment by VocsyAniket** [comment]
> @VocsyAniket can I get the output for `flutter doctor` ?

![Screenshot at Jul 08 11-23-35](https://github.com/webrror/watchos_flutter_test/assets/113010923/94a3dd82-3e82-40e7-a22e-b80e5fe55458)


which one select ?

**Comment by VocsyAniket** [comment]
``Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Kaushik’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues `found!`

**Comment by webrror** [comment]
> > @VocsyAniket can I get the output for `flutter doctor` ?
> 
> ![Screenshot at Jul 08 11-23-35](https://github.com/webrror/watchos_flutter_test/assets/113010923/94a3dd82-3e82-40e7-a22e-b80e5fe55458)
> 
> 
> which one select ?
> 

You have to select "Watch App for Existing iOS App" and select Runner of your Flutter app.

**Comment by VocsyAniket** [comment]
> > > @VocsyAniket can I get the output for `flutter doctor` ?
> > 
> > 
> > ![Screenshot at Jul 08 11-23-35](https://private-user-images.githubusercontent.com/113010923/346443254-94a3dd82-3e82-40e7-a22e-b80e5fe55458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTk4MDQsIm5iZiI6MTcyMDQxOTUwNCwicGF0aCI6Ii8xMTMwMTA5MjMvMzQ2NDQzMjU0LTk0YTNkZDgyLTNlODItNDBlNy1hMjJlLWI4MGU1ZmU1NTQ1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNjE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDM0NDQ5NDhmZGI3YjEzZDhlNWI0ZGY1MmNkMTlmYTZjYWZiN2I4ODczNTQ4OWVlYzhmMTZiNzE4NDU5ZWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H07jMQkiK6gfkrn6eANSCAlYR57oNgsm7gQY8Mr4FS0)
> > which one select ?
> 
> You have to select "Watch App for Existing iOS App" and select Runner of your Flutter app.

i am already Watch App for Existing iOS App select,
i am using your git project but watch to iphone in send message perfect but iphone to watch send message not working

**Comment by VocsyAniket** [comment]
https://github.com/webrror/watchos_flutter_test/assets/113010923/16717541-240e-4367-bd3f-ee03b6f0a208

show this video

**Comment by webrror** [comment]
@VocsyAniket any error/info in console? Any code I can take a look at?

I have no issues running on both Flutter 3.19.6 and 3.22.2

**Comment by VocsyAniket** [comment]
> @VocsyAniket any error/info in console? Any code I can take a look at?
> 
> I have no issues running on both Flutter 3.19.6 and 3.22.2

no error and no console in anything print

**Comment by VocsyAniket** [comment]
can i share my code so you can find the error or issue ?
i will send github link

**Comment by webrror** [comment]
@VocsyAniket 

Alright from the video I see you are running your iOS app from xcode.

The correct way that worked for me was to run the **watch app from xcode** while **iOS app needs to be run using `flutter run` or from your IDE** in my case it's vscode.

While I tried running both from XCode, I got a log in the xcode console saying `watch not reachable`

Could you check if this is the case for you?

**Comment by VocsyAniket** [comment]
xcode console saying watch not reachable

So what do I do for this issue

**Comment by webrror** [comment]
> @VocsyAniket 
> 
> Alright from the video I see you are running your iOS app from xcode.
> 
> The correct way that worked for me was to run the **watch app from xcode** while **iOS app needs to be run using `flutter run` or from your IDE** in my case it's vscode.
> 
> While I tried running both from XCode, I got a log in the xcode console saying `watch not reachable`
> 
> Could you check if this is the case for you?

In addition to that, for me order in which I ran the apps mattered too.

For instance, I had to run the watch app from xcode first then the iOS app from my IDE.

**Comment by jerinj-eloit** [comment]
> xcode console saying watch not reachable
> 
> So what do I do for this issue

The correct way that worked for me was to run the watch app from xcode while iOS app needs to be run using flutter run or from your IDE in my case it's vscode.

**Comment by webrror** [comment]
> xcode console saying watch not reachable
> 
> So what do I do for this issue

The correct way that worked for me was to run the watch app from xcode while iOS app needs to be run using flutter run or from your IDE in my case it's vscode.

I had to run the watch app from xcode first then the iOS app from my IDE.

**Comment by VocsyAniket** [comment]
can you get my any desk screen sharing so you can properly find that error ?

**Comment by webrror** [comment]
> > xcode console saying watch not reachable
> > 
> > So what do I do for this issue
> 
> The correct way that worked for me was to run the watch app from xcode while iOS app needs to be run using flutter run or from your IDE in my case it's vscode.
> 
> I had to run the watch app from xcode first then the iOS app from my IDE.

@VocsyAniket Please try to follow this.

**Comment by VocsyAniket** [comment]
you can say like 
i have run watchos app from xcode and ios app run from android studio ?

**Comment by webrror** [comment]
> you can say like 
> i have run watchos app from xcode and ios app run from android studio ?

Yes

First run watch app from xcode

Then iOS/Flutter app from Android studio

**Comment by VocsyAniket** [comment]
https://github.com/webrror/watchos_flutter_test/assets/113010923/8b0bcedd-d024-4b5e-b962-2194d5b9e92f

show this video
first time both app install after this console in show the error, but second time both app run when no error show in console, how ?

**Comment by webrror** [comment]
https://github.com/webrror/watchos_flutter_test/assets/65507007/85ae6214-5b42-4dc3-91d9-2ad4ea7f3cd1

**Comment by VocsyAniket** [comment]
give me your watchos and phone app xcode in show me settings ?

**Comment by webrror** [comment]
> give me your watchos and phone app xcode in show me settings ?

What specifically do you want to see?

**Comment by VocsyAniket** [comment]
![image](https://github.com/webrror/watchos_flutter_test/assets/113010923/d8d9cd46-76ea-4c19-9eee-ed5c1d523d58)

both app in general and build phases

**Comment by webrror** [comment]
General

![tmp_584582e8-ee49-49ab-89ef-c9a9d8422342.png](https://github.com/webrror/watchos_flutter_test/assets/65507007/e9fbc8c1-665e-4fb1-968f-17132cbce3d0)

![tmp_9c3c1344-eaa6-4b2e-ad99-db0c905e4b34.png](https://github.com/webrror/watchos_flutter_test/assets/65507007/be1222a3-995a-43c8-9e76-4b1683e32ad2)

Build phases

![tmp_3232418c-0fc0-40c5-9514-2ccb1efd5179.png](https://github.com/webrror/watchos_flutter_test/assets/65507007/dd6b0810-69ed-46c6-9c85-5892bf637df8)

![tmp_e71c054f-e3af-4640-ada1-44d57c3872f7.png](https://github.com/webrror/watchos_flutter_test/assets/65507007/18708e32-f4a5-4e6b-8652-efd2dcb3b171)

**Comment by VocsyAniket** [comment]
same as settings but not working please help me out of this issues,
can you fix this issue you can any desk screen sharing and fix this problem ?

**Comment by webrror** [comment]
Share link to your source code.

**Comment by VocsyAniket** [comment]
https://github.com/VocsyAniket/flutter_watchOS.git

**Comment by webrror** [comment]
@VocsyAniket 

In your `main.dart` file on line 36, you have

```
final MethodChannel _channel = const MethodChannel("com.example.appleTest4");
```

Could you try replacing the package name with your own app's package name?

In your case: `com.watchos.watchosDemo`

**Comment by VocsyAniket** [comment]
`com.watchos.watchosDemo` replace this own package name but not working

**Comment by webrror** [comment]
https://github.com/webrror/watchos_flutter_test/assets/65507007/0cb93eab-8272-492c-b6e4-1a3a5b19429b

I have no issues running your shared app. Everything works as expected.

Once again please make sure you are running in the above said order.

First watch app from xcode

Then flutter app from Android studio

**Comment by VocsyAniket** [comment]
check your mail sending screen recording

**Comment by VocsyAniket** [comment]
![image](https://github.com/webrror/watchos_flutter_test/assets/113010923/baf692fb-7845-47fc-85ec-3ef33930ba67)

This is how you have created the simulator

**Comment by webrror** [comment]
> ![image](https://github.com/webrror/watchos_flutter_test/assets/113010923/baf692fb-7845-47fc-85ec-3ef33930ba67)
> 
> This is how you have created the simulator

Yes

**Comment by VocsyAniket** [comment]
![image](https://github.com/webrror/watchos_flutter_test/assets/113010923/1ea987af-7e2b-4c6e-8d53-5fd0e4f38c22)

i have change this version older and after this version latest after both watch and iphone in data send successfully

**Comment by webrror** [comment]
> ![image](https://github.com/webrror/watchos_flutter_test/assets/113010923/1ea987af-7e2b-4c6e-8d53-5fd0e4f38c22)
> 
> i have change this version older and after this version latest after both watch and iphone in data send successfully
> 

Ohh I see. I see that mine is also set to a lower 9.1.

I was not aware that it would affect the working of the app.

Glad you figured it out.

Have a nice day😊

**Comment by webrror** [comment]
Closing

**Comment by VocsyAniket** [comment]
Hii Brother,

```
extension WatchViewModel: WCSessionDelegate {
    func session(_ session: WCSession, activationDidCompleteWith activationState: WCSessionActivationState, error: Error?) { }
    func session(_ session: WCSession, didReceiveMessage message: [String: Any]) {
        print("did receive message ------")
        guard let method = message["method"] as? String, let data = message["data"] as? [String: Any] else { return }

        guard method == "updateTextFromFlutter", let drinkWater = data["drinkWater"] as? Int, let remainingWater = data["remainingWater"] as? Int, let waterPercentage = data["waterPercentage"] as? String, let waterProgress = data["waterProgress"] as? Double else { return }

        Task { @MainActor in
            self.drinkWater = drinkWater
            self.remainingWater = remainingWater
            self.waterPercentage = waterPercentage
            self.waterProgress = waterProgress
        }
    }
}
```

i don't know why phone to watch data send in this didReceiveMessage function not call,
my project in same to same implement but not working
demo project in working, why my project in not working i don't understand
