### ISSUE TITLE
Receive Method not Working in WatchOS

### ISSUE THREAD

**Issue by VocsyAniket** [webrror/watchos_flutter_test#3]
Can you share a full video how to implement everything related to your project
From project creation to watchOS implementation, you can create and share a video of the entire setup.
please help me out of this situation

**Comment by webrror** [comment]
Hi,

You can take a look at the talk and medium article which I followed to achieve this.

### <a href="https://www.youtube.com/watch?v=l1-QYqaGyMk">Flutter Vikings 2022 talk by Michael Hitzker</a> | <a href="https://github.com/michaelhitzker/flutter-vikings-2022">Repo</a>

### <a href="https://medium.com/kbtg-life/adding-apple-watch-to-flutter-app-via-flutter-method-channel-f1443532d94e">Article by Amorn Apichattanakul</a> | <a href="https://github.com/theamorn/flutter-apple-watch">Repo</a>

I have done nothing new apart from changing the buttons.
